apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-app
  name: dev-simple-app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: simple-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app
  name: dev-simple-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - image: gcr.io/mv-service-project-7215/simple-app:0c79346e74ec8e848c95fe9f2fad419d3f5b20b9
        name: simple-app
