name: Remove PR Branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to delete'
        required: true
        default: ''


jobs:
  remove-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
         git push origin --delete ${{ github.event.inputs.branch }}
