# This is a basic workflow to help you get started with Actions

name: Update App Version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the app to deploy'
        required: true
        default: ''
      branch:
        description: 'Branch to checkout to'
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      
      # Runs a single command using the runners shell
      - name: Output CI Inputs
        run: echo "App version ${{ github.event.inputs.version }}, Branch ${{ github.event.inputs.branch }}"
        
      - name: Set version
        run: echo ${{ github.event.inputs.version }} > version
        
      - name: Push changes
        uses: actions-go/push@v1
        with:
          ref: ${{ github.event.inputs.branch }}
          commit-message: "CI triggered new version"
          remote-ref: ${{ github.event.inputs.branch }}

